on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: View python version
      run: |
        python --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Delete gh-pages branch
      run: |
        git branch -d gh-pages || true

    - name: Create gh-pages branch
      run: |
        git branch gh-pages && git switch gh-pages

    # Build the book
    - name: Build and copy contents
      run: |
        jupyter-book build .
        mv _build/html docs
        cp -r docs_static/* docs/

    - name: List contents
      run: |
        ls -la docs/

    - name: Update the site
      run: |
        git config user.name "Git Runner"
        git config user.email "35618518+leangaurav@users.noreply.github.com"
        git add docs
        git status
        git commit -m "Update site content"
        git push
